/** بيانات تجريبية — بتشتغل لحد ما تربط Supabase (حط المفاتيح في .env.local) */

import type { Property } from "./types";

const P = (p: Partial<Property> & { id: string; title: string; price: number }): Property => ({
  created_at: new Date(Date.now() - Math.floor(Math.random() * 40) * 86400000).toISOString(),
  listing_type: "sale",
  rent_period: null,
  property_type: "شقة",
  description:
    "عقار مميز في موقع استراتيجي، تشطيب سوبر لوكس، قريب من كل الخدمات والمواصلات. مناسبة للعائلات وللاستثمار.",
  governorate: "القاهرة",
  city: "مدينة نصر",
  district: "عباس العقاد",
  area: 140,
  bedrooms: 3,
  bathrooms: 2,
  features: ["مصعد", "جراج خاص"],
  images: [],
  contact_phone: "01556956343",
  is_featured: false,
  is_published: true,
  ...p,
});

const img = (seed: string, w = 800, h = 600) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const MOCK_PROPERTIES: Property[] = [
  P({
    id: "mock-1",
    title: "شقة 140م سوبر لوكس بمدينة نصر - عباس العقاد",
    price: 2750000,
    area: 140,
    bedrooms: 3,
    bathrooms: 2,
    images: [img("nasr1"), img("nasr1b"), img("nasr1c")],
    is_featured: true,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  }),
  P({
    id: "mock-2",
    title: "فيلا مستقلة بحمام سباحة - التجمع الخامس",
    property_type: "فيلا",
    price: 12500000,
    governorate: "القاهرة",
    city: "التجمع الخامس",
    district: "الحي الخامس",
    area: 400,
    bedrooms: 5,
    bathrooms: 4,
    features: ["مسبح", "حديقة", "جراج خاص", "أمن وحراسة"],
    images: [img("villa2"), img("villa2b"), img("villa2c")],
    is_featured: true,
  }),
  P({
    id: "mock-3",
    title: "شقة للإيجار المفروش 120م - المهندسين",
    listing_type: "rent",
    rent_period: "monthly",
    price: 18000,
    governorate: "الجيزة",
    city: "المهندسين",
    district: "جامعة الدول",
    area: 120,
    bedrooms: 2,
    bathrooms: 2,
    features: ["مصعد", "مطبخ مجهز", "تكييف مركزي"],
    images: [img("mohand3"), img("mohand3b")],
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  }),
  P({
    id: "mock-4",
    title: "محل تجاري 60م على شارع رئيسي - المعادي",
    property_type: "محل تجاري",
    price: 4500000,
    governorate: "القاهرة",
    city: "المعادي",
    district: "المعادي الجديدة",
    area: 60,
    bedrooms: 0,
    bathrooms: 1,
    features: [],
    images: [img("shop4")],
  }),
  P({
    id: "mock-5",
    title: "شاليه 100م على البحر - الساحل الشمالي",
    property_type: "شاليه",
    price: 3500000,
    governorate: "مطروح",
    city: "الساحل الشمالي",
    district: "مارينا",
    area: 100,
    bedrooms: 2,
    bathrooms: 2,
    features: ["مسبح", "أمن وحراسة", "حديقة"],
    images: [img("chalet5"), img("chalet5b")],
    is_featured: true,
  }),
  P({
    id: "mock-6",
    title: "استوديو مفروش 55م للإيجار - الشيخ زايد",
    property_type: "ستوديو",
    listing_type: "rent",
    rent_period: "monthly",
    price: 9000,
    governorate: "الجيزة",
    city: "الشيخ زايد",
    district: "الحي الثاني",
    area: 55,
    bedrooms: 1,
    bathrooms: 1,
    features: ["مصعد", "إنترنت فايبر"],
    images: [img("studio6"), img("studio6b")],
  }),
  P({
    id: "mock-7",
    title: "دوبلكس 220م رووف خاص - مصر الجديدة",
    property_type: "دوبلكس",
    price: 6800000,
    governorate: "القاهرة",
    city: "مصر الجديدة",
    district: "الكوربة",
    area: 220,
    bedrooms: 4,
    bathrooms: 3,
    features: ["جراج خاص", "شرفة واسعة", "مطبخ مجهز"],
    images: [img("duplex7"), img("duplex7b"), img("duplex7c")],
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  }),
  P({
    id: "mock-8",
    title: "شقة 150م بالدور الرابع - سموحة الإسكندرية",
    price: 1900000,
    governorate: "الإسكندرية",
    city: "سموحة",
    district: "سيدي جابر",
    area: 150,
    bedrooms: 3,
    bathrooms: 2,
    features: ["مصعد", "قريب من المواصلات"],
    images: [img("alex8"), img("alex8b")],
  }),
  P({
    id: "mock-9",
    title: "مكتب إداري مجهز 90م - العاشر من رمضان",
    property_type: "مكتب إداري",
    listing_type: "rent",
    rent_period: "yearly",
    price: 120000,
    governorate: "الشرقية",
    city: "العاشر من رمضان",
    district: "الحي الثالث",
    area: 90,
    bedrooms: 0,
    bathrooms: 2,
    features: ["تكييف مركزي", "أمن وحراسة", "إنترنت فايبر"],
    images: [img("office9")],
  }),
  P({
    id: "mock-10",
    title: "أرض 500م للبناء - أكتوبر الجديدة",
    property_type: "أرض",
    price: 2250000,
    governorate: "الجيزة",
    city: "6 أكتوبر",
    district: "الحي المتميز",
    area: 500,
    bedrooms: 0,
    bathrooms: 0,
    features: [],
    images: [img("land10")],
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  }),
  P({
    id: "mock-11",
    title: "شقة 130م للإيجار السنوي - طنطا",
    listing_type: "rent",
    rent_period: "yearly",
    price: 42000,
    governorate: "الغربية",
    city: "طنطا",
    district: "المشروع",
    area: 130,
    bedrooms: 3,
    bathrooms: 1,
    features: ["مصعد"],
    images: [img("tanta11")],
  }),
  P({
    id: "mock-12",
    title: "رووف 160م بحديقة خاصة - مدينتي",
    property_type: "رووف",
    price: 4900000,
    governorate: "القاهرة",
    city: "مدينتي",
    district: "أبني بيتك",
    area: 160,
    bedrooms: 3,
    bathrooms: 2,
    features: ["حديقة", "جراج خاص", "أمن وحراسة"],
    images: [img("roof12"), img("roof12b")],
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  }),
];
